name: run-with-dynamic-shell

description: |
  Workaround for https://github.com/actions/runner/issues/444.
  By going through an action, we can actually use a matrix variable in the shell parameter.

inputs:
  run:
    required: true
  shell:
    required: true

runs:
  using: 'composite'
  steps:
    - name: "Run with dynamic shell: ${{ inputs.shell }}"
      shell: ${{ inputs.shell }}
      run: ${{ inputs.run }}
